### ISSUE TITLE
Gets stuck on Melon js load screen

### ISSUE THREAD

**Issue by coreybruce** [radmars/ld35#1]
Cannot play games as it gets stuck on melon js screen when opened and does nothing.

http://i.imgur.com/RZotUuE.png

**Comment by emarcotte** [comment]
@gameslayer, what browser are you using? Does the console have any output?

**Comment by coreybruce** [comment]
Google Chrome on Xubuntu 16.04, what output am I looking for?

**Comment by emarcotte** [comment]
Any errors really, or if it's still downloading assets in the network tab (the audio can take quite some time to download)

**Comment by coreybruce** [comment]
I did find a whole bunch of errors in the console having trouble loading the levels.
http://i.imgur.com/26RHBAC.png

I did also try another Melon JS game and it didn't load up either and most likely is the same issue.

**Comment by emarcotte** [comment]
Ah, yeah when you load assets via melon they are done via https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest so you need to actually run a web server.

Since your on ubuntu, you probably have python available, try running: `python -m SimpleHTTPServer 8000`

in the directory with index.html and opening `localhost:8080` in your browser.

(https://docs.python.org/2/library/simplehttpserver.html)

**Comment by coreybruce** [comment]
Ah I see so why do I need to start a Server just to run this and why can't I just load it up like a normal html file I was going to test it out and make a Electron application with it but I see a lot more work is needed just to launch the game.

I ran that command but nothing is happening.

**Comment by emarcotte** [comment]
Likely electron has some facility to load resources. We've not explored that option as we make games for the browsers/sites to avoid having to figure out how to deploy them.

I'd suggest reading through: http://melonjs.github.io/melonJS/docs/

**Comment by coreybruce** [comment]
"Standalone library (does not rely on anything else, except a HTML5 capable browser)
Compatible with most major browser (Chrome, Safari, Firefox, Opera, IE) and mobile devices"

Well even so it is based on Chromium but I can't run it on Chrome browser without needing to run a Python server even tho it says doesn't rely on anything but a html 5 capable browser which Chrome certainly is so why do I need to do this just to run the game?

**Comment by emarcotte** [comment]
You should probably raise this question with the MelonJS team, we just wrote a game using it.
